version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    ports:
      - "3000:80" # Mapea el puerto 3000 del host al puerto 80 del contenedor
      - "53:53/tcp" # Para el tráfico DNS TCP
      - "53:53/udp" # Para el tráfico DNS UDP
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  wg-easy:
    depends_on: [adguard]
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid # Change to your timezone
      - PASSWORD=${PASSWORD} # Cambia YOUR_ADMIN_PASSWORD por una contraseña segura
      - WG_HOST=${WG_HOST} # Cambia YOUR_SERVER_IP por tu dirección IP o dominio 
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.2.0.100 # Set it to point to adguard home
      - INTERNAL_SUBNET=10.6.0.0
    volumes:
      - "./wg-easy:/etc/wireguard"
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp" # Puerto para la interfaz web de wg-easy
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3 # Asegúrate de que esta dirección IP no está en conflicto con otros servicios
